title: Christo nihil praeponere
author:
  name: GitHub @Araguaci
  email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Christo nihil praeponere. A nada dar mais valor que a Cristo. A nada dar mais valor que ao seu amor, exatamente porque Cristo a nada deu mais valor que a nós.

theme: jekyll-theme-minimal
